merge-key: "fyre-dev/sremat-test1/inst1"
ibm_mas_suite_configs:
  - mas_config_name: "inst1-sls-system"
    mas_config_chart: ibm-mas-sls-config
    mas_config_scope: system
    mas_workspace_id: aibroker
    mas_application_id:
    mas_config_kind: "slscfgs"
    mas_config_api_version: "config.mas.ibm.com"
    use_postdelete_hooks: true
    registration_key: <path::fyre-dev/abc12345/sls-params.yaml/sls#registration_key>
    url: <path::fyre-dev/abc12345/sls-params.yaml/sls#sls_url>
    ca:
      crt: |
        <path::fyre-dev/abc12345/sls-params.yaml/sls#ca_b64 | base64decode>
