merge-key: "fyre-dev/sremat-test1/sls01"
ibm_mas_suite_configs:
  - mas_config_name: "sls01-sls-system"
    mas_config_chart: ibm-mas-sls-config
    mas_config_scope: system
    mas_workspace_id: aibroker
    mas_application_id:
    mas_config_kind: "slscfgs"
    mas_config_api_version: "config.mas.ibm.com"
    use_postdelete_hooks: true
    registration_key: <path::fyre-dev/sremat-test1/sls01/sls#registration_key>
    url: "https://sls.mas-sls01-sls.svc"
    ca:
      crt: |
        <path::fyre-dev/sremat-test1/sls01/sls#ca_b64 | base64decode>
