merge-key: "fyre-dev/sremat-test1/inst01"
ibm_mas_suite_configs:
  - mas_config_name: "inst01-jdbc-system"
    mas_config_chart: ibm-jdbc-config
    mas_config_scope: system
    mas_workspace_id: aibroker
    mas_application_id:
    mas_config_kind: "jdbccfgs"
    mas_config_api_version: "config.mas.ibm.com"
    use_postdelete_hooks: true
    jdbc_type: incluster-db2
    jdbc_connection_url_additional_params: secure=true
    jdbc_instance_name: <path::fyre-dev/sremat-test1/inst01/jdbc/db2wh-inst01-/config#jdbc_instance_name>
    jdbc_instance_username: <path::fyre-dev/sremat-test1/inst01/jdbc/db2wh-inst01-/credentials#username>
    jdbc_instance_password: <path::fyre-dev/sremat-test1/inst01/jdbc/db2wh-inst01-/credentials#password>
    mas_config_dir:
    jdbc_connection_url: <path::fyre-dev/sremat-test1/inst01/jdbc/db2wh-inst01-/config#jdbc_connection_url>
    jdbc_route: default
    db2_dbname: <path::fyre-dev/sremat-test1/inst01/jdbc/db2wh-inst01-/config#db2_dbname>
    db2_namespace: <path::fyre-dev/sremat-test1/inst01/jdbc/db2wh-inst01-/config#db2_namespace>
    app_suite_jdbccfg_labels:
      mas.ibm.com/applicationId: ""
      mas.ibm.com/configScope: application
      mas.ibm.com/instanceId: "inst01"
    system_suite_jdbccfg_labels:
      mas.ibm.com/configScope: system
      mas.ibm.com/instanceId: "inst01"
    ws_suite_jdbccfg_labels:
      mas.ibm.com/configScope: workspace-application
      mas.ibm.com/instanceId: "inst01"
      mas.ibm.com/workspaceId: "aibroker"
    wsapp_suite_jdbccfg_labels:
      mas.ibm.com/applicationId: ""
      mas.ibm.com/configScope: workspace-application
      mas.ibm.com/instanceId: "inst01"
      mas.ibm.com/workspaceId: "aibroker"
    jdbc_ca_pem:
      crt: |
        <path::fyre-dev/sremat-test1/inst01/jdbc/db2wh-inst01-/config#ca_b64 | base64decode>
